name: Create Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create ZIP file
        run: |
          git ls-files | grep -v '^\.github/' | xargs zip dependencies.zip

      ### Getting either the git tag or branch name to be set in the json
      - name: Get the version
        id: get_version
        run: |
          echo "VERSION=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_OUTPUT
          echo "releasetag=$VERSION" >> $GITHUB_ENV

      ### Upload to GitHub releases
      - name: Release to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            **.zip
          fail_on_unmatched_files: true
          name: ${{ env.releasetag }}
          tag_name: ${{ env.releasetag }}
          generate_release_notes: true
          prerelease: false
